namespace: dinesh
replicas: 1

elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    containerPort: 9200
    appName: elasticsearch
    volumeMountsName: elasticsearch-data
    volumeMountsPath: /usr/share/elasticsearch/data
    
searchBackend:
    image: dineshsonachalam/tech-courses-search-engine-backend:latest
    containerPort: 8000
    appName: search-backend
    ingressRoute: (Host(`api-search.dineshsonachalam.com`))

searchFrontend:
    image: dineshsonachalam/tech-courses-search-engine-frontend:latest
    containerPort: 3000   
    appName: search-frontend
    ingressRoute: (Host(`search.dineshsonachalam.com`))
